WIP: Fixed most of the build and dependencies issues on macos

diff --git a/native/bin/build b/native/bin/build
--- a/native/bin/build
+++ b/native/bin/build
@@ -30,9 +30,22 @@ else
 fi
 
 CURRENT_DIR=$(pwd)
-WORK_DIR=`mktemp -d`
+TMP_DIR=`mktemp -d`
+WORK_DIR="${HOME}/.trinity-native"
 
-trap "echo 'Cleaning up and exiting...' && rm -rf ${WORK_DIR} && cd ${CURRENT_DIR}" EXIT
+function stop_script () {
+  ERROR=$1
+  if [ ! -z "${ERROR}" ]
+  then
+    echo "Encountered an error: ${ERROR}"
+    echo "Exiting..."
+  else
+    echo 'Cleaning up and exiting...'
+  fi
+  rm -rf ${TMP_DIR} 
+  exit 1
+}
+trap stop_script EXIT
 
 function setup_python3 () {
   echo "Checking whether Python3 is installed..."
@@ -43,10 +56,10 @@ function setup_python3 () {
     echo "Python3 is not installed on this system. Installing python3..."
     case `uname` in
       Linux )
-        sudo apt-get install python3.8 python3-pip -y
+        sudo apt-get install python3.8 python3-pip -y || stop_script "Cannot install python3"
       ;;
       Darwin )
-        brew install sashkab/python/python@3.8
+        brew install sashkab/python/python@3.8 || stop_script "Cannot install python3"
         ln -s /usr/local/opt/python@3.8/bin/python3.8 /usr/local/bin/python3.8
       ;;
     esac
@@ -79,7 +92,7 @@ function setup_openjdk8 () {
     then
       echo "Using Java ${version} for build"
     else       
-      found_jdk8 ="no"
+      found_jdk8="no"
       echo "Found incompatible OpenJDK version: ${version}. Installing OpenJDK8"
     fi
   fi
@@ -88,19 +101,21 @@ function setup_openjdk8 () {
   then
     case `uname` in
       Linux )
-        sudo apt-get install openjdk-8-jdk -y
+        sudo apt-get install openjdk-8-jdk -y || stop_script "Cannot install openjdk8"
+        java_home_path="/usr/lib/jvm/java-8-openjdk-amd64"
       ;;
       Darwin )
-        brew tap AdoptOpenJDK/openjdk
-        brew cask install adoptopenjdk8
+        brew tap AdoptOpenJDK/openjdk || stop_script "Cannot install openjdk8"
+        brew cask install adoptopenjdk8 || stop_script "Cannot install openjdk8"
+        java_home_path="/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home"
       ;;
     esac
+
     echo "Setting up JAVA_HOME and adding it to PATH"
-    echo "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64"
-    export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
-    if [ -z $(cat ${HOME}/.bash_profile | grep "JAVA_HOME PATH added by Elastos.Trinity Toolchain") ]
+    EXIST_ON_BASHPROFILE=$(cat ${HOME}/.bash_profile | grep "JAVA_HOME PATH added by Elastos.Trinity Toolchain")
+    if [ -z "${EXIST_ON_BASHPROFILE}" ]
     then
-      printf "\n# JAVA_HOME PATH added by Elastos.Trinity Toolchain Build Process\nexport JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64\n" >> ${HOME}/.bash_profile
+      printf "\n# JAVA_HOME PATH added by Elastos.Trinity Toolchain Build Process\nexport JAVA_HOME=${java_home_path}\n" >> ${HOME}/.bash_profile
     fi
     source ${HOME}/.bash_profile
     echo "Using Java $(java -version) for build"
@@ -133,7 +148,14 @@ function setup_nodejs () {
 
   if [[ $(echo ${found_nodejs}) == "no" ]]
   then
-    curl https://deb.nodesource.com/setup_12.x | bash
+    case `uname` in
+      Linux )
+        sudo apt-get install node npm -y || stop_script "Cannot install NodeJS"
+      ;;
+      Darwin )
+        brew install node || stop_script "Cannot install NodeJS"
+      ;;
+    esac
     echo "Using NodeJS ${version} and Npm $(npm -v) for build"
     echo "Setting up Npm path at ${HOME}/.npm-global and adding it to PATH temporarily"
     mkdir -p ${HOME}/.npm-global
@@ -150,7 +172,13 @@ function setup_android_sdkmanager () {
   if [[ $(type -p sdkmanager) ]]
   then
     echo "Found Android Sdkmanager"
-    export ANDROID_SDK_ROOT=$(echo $(${READLINK} -f $(which sdkmanager)) | ${SED} 's#/cmdline-tools/tools/bin/sdkmanager##g')
+    if [ "$(uname)" == "Linux" ]
+    then 
+      prefix=""
+    else
+      prefix="cmdline-"
+    fi 
+    export ANDROID_SDK_ROOT=$(echo $(${READLINK} -f $(which sdkmanager)) | ${SED} "s#/cmdline-tools/${prefix}/bin/sdkmanager##g")
   else
     found_sdkmanager="no"
     echo "Android Sdkmanager is not installed on this system. Installing Android Sdkmanager at ${HOME}/android/android-sdk..."   
@@ -159,25 +187,26 @@ function setup_android_sdkmanager () {
   if [[ $(echo ${found_sdkmanager}) == "no" ]]
   then
     rm -rf ${HOME}/android/android-sdk/cmdline-tools
-    mkdir -p ${HOME}/android/android-sdk/cmdline-tools   
-    case `uname` in
-      Linux )                                                     
-        wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip -P ${WORK_DIR} &&  \
-        yes | unzip -d ${HOME}/android/android-sdk/cmdline-tools ${WORK_DIR}/commandlinetools-linux-*.zip
-      ;;
-      Darwin )
-        wget https://dl.google.com/android/repository/commandlinetools-mac-6858069_latest.zip -P ${WORK_DIR} &&  \
-        yes | unzip -d ${HOME}/android/android-sdk/cmdline-tools ${WORK_DIR}/commandlinetools-mac-*.zip
-      ;;
-    esac
+    mkdir -p ${HOME}/android/android-sdk   
+    if [ "$(uname)" == "Linux" ]
+    then 
+      file_name="commandlinetools-linux-6858069_latest.zip"
+      android_cmdline_path="cmdline-tools/tools/bin"
+    else
+      file_name="commandlinetools-mac-6858069_latest.zip"
+      android_cmdline_path="cmdline-tools/cmdline-tools/bin"
+    fi
+    wget https://dl.google.com/android/repository/${file_name} -P ${TMP_DIR} || stop_script "Cannot download Android Sdkmanager"
+    yes | unzip -d ${HOME}/android/android-sdk/cmdline-tools ${TMP_DIR}/${file_name} || stop_script "Cannot install Android Sdkmanager"
     echo "Setting up ANDROID_SDK_ROOT and adding it to PATH"
     echo "export ANDROID_SDK_ROOT=${HOME}/android/android-sdk"
     export ANDROID_SDK_ROOT=${HOME}/android/android-sdk
-    export PATH="${PATH}:${ANDROID_SDK_ROOT}/cmdline-tools/tools/bin"
-    if [ -z $(cat ${HOME}/.bash_profile | grep "ANDROID_SDK_ROOT PATH added by Elastos.Trinity Toolchain") ]
+    export PATH="${PATH}:${ANDROID_SDK_ROOT}/${android_cmdline_path}"
+    EXIST_ON_BASHPROFILE=$(cat ${HOME}/.bash_profile | grep "ANDROID_SDK_ROOT PATH added by Elastos.Trinity Toolchain")
+    if [ -z "${EXIST_ON_BASHPROFILE}" ]
     then
       printf "\n# ANDROID_SDK_ROOT PATH added by Elastos.Trinity Toolchain Build Process\nexport ANDROID_SDK_ROOT=${HOME}/android/android-sdk\n" >> ${HOME}/.bash_profile
-      echo 'export PATH="${PATH}:${ANDROID_SDK_ROOT}/cmdline-tools/tools/bin"' >> ${HOME}/.bash_profile
+      echo 'export PATH="${PATH}:${ANDROID_SDK_ROOT}/'${android_cmdline_path}'"' >> ${HOME}/.bash_profile
     fi   
     source ${HOME}/.bash_profile
   fi  
@@ -189,9 +218,6 @@ function setup_android_sdkmanager () {
       "build-tools;28.0.3" "platform-tools" "platforms;android-28" "ndk;21.3.6528147" &&          \
   yes | sdkmanager --licenses 
   wait
-
-  echo "Setting Android Sdkmanager tools path temporarily"
-  export PATH="${PATH}:${ANDROID_SDK_ROOT}/tools:${ANDROID_SDK_ROOT}/platform-tools" 
 }
 
 function setup_android_gradle () {
@@ -224,15 +250,16 @@ function setup_android_gradle () {
   if [[ $(echo ${found_gradle}) == "no" ]]
   then
     mkdir -p ${HOME}/android
-    rm -rf ${HOME}/android/gradle &&                                                        \
-    wget https://services.gradle.org/distributions/gradle-6.7-bin.zip -P ${WORK_DIR} &&     \
-    yes | unzip -d ${HOME}/android ${WORK_DIR}/gradle-6.7-bin.zip &&                        \
-    mv ${HOME}/android/gradle-6.7 ${HOME}/android/gradle &&                                 \
-    echo "Setting up GRADLE_HOME and adding it to PATH" &&                                  \
-    echo "export GRADLE_HOME=${HOME}/android/gradle" &&                                     \
+    rm -rf ${HOME}/android/gradle
+    wget https://services.gradle.org/distributions/gradle-6.7-bin.zip -P ${TMP_DIR} || stop_script "Cannot download Android Gradle"
+    yes | unzip -d ${HOME}/android ${TMP_DIR}/gradle-6.7-bin.zip || stop_script "Cannot install Android Gradle"
+    mv ${HOME}/android/gradle-6.7 ${HOME}/android/gradle
+    echo "Setting up GRADLE_HOME and adding it to PATH" 
+    echo "export GRADLE_HOME=${HOME}/android/gradle"
     export GRADLE_HOME=${HOME}/android/gradle   
     export PATH="${PATH}:${GRADLE_HOME}/bin"
-    if [ -z $(cat ${HOME}/.bash_profile | grep "GRADLE_HOME PATH added by Elastos.Trinity Toolchain") ]
+    EXIST_ON_BASHPROFILE=$(cat ${HOME}/.bash_profile | grep "GRADLE_HOME PATH added by Elastos.Trinity Toolchain")
+    if [ -z "${EXIST_ON_BASHPROFILE}" ]
     then
       printf "\n# GRADLE_HOME PATH added by Elastos.Trinity Toolchain Build Process\nexport GRADLE_HOME=${HOME}/android/gradle\n" >> ${HOME}/.bash_profile
       echo 'export PATH="${PATH}:${GRADLE_HOME}/bin"' >> ${HOME}/.bash_profile
@@ -243,15 +270,15 @@ function setup_android_gradle () {
 }
 
 function preinstall () {
-  echo "Installing dependencies for basic tools..."
+  echo "Installing basic dependencies and tools..."
   # Update the package manager and install the essential build tools
   case `uname` in
     Linux )
       if [ "${UPDATE}" == "yes" ]
       then
-        sudo apt-get update -y 
+        sudo apt-get update -y
       fi
-      sudo apt-get install build-essential -y
+      sudo apt-get install build-essential wget curl -y || stop_script "Cannot install basic dependencies"
       READLINK=$(which readlink)
       SED=$(which sed)
     ;;
@@ -260,9 +287,10 @@ function preinstall () {
       then
         brew update
       fi
-      brew install coreutils gnu-sed
+      brew install coreutils gnu-sed wget curl || stop_script "Cannot install basic dependencies"
       READLINK=$(which greadlink)
       SED=$(which gsed)
+
     ;;
     *)
       echo "This script can only run on Linux or Darwin machines. Exiting..."
@@ -273,7 +301,7 @@ function preinstall () {
 
 function install_dependencies () {
   echo "Setting up python virtual environment at ${HOME}/.venv"
-  pip3 install virtualenv
+  pip3 install --user virtualenv
   virtualenv -p `which python3` ${HOME}/.venv
   source ${HOME}/.venv/bin/activate
   pip install --upgrade pip
@@ -284,10 +312,15 @@ function install_dependencies () {
     cordova-res@0.15.1                                    \
       @ionic/cli@6.12.1                                   \
       typescript@4.0.5                                    \
-      @elastosfoundation/trinity-cli@1.1.34
+      @elastosfoundation/trinity-cli@1.1.34  || stop_script "Cannot install npm dependencies"
 
   echo "Cloning Elastos.Trinity github repository..."
-  git clone --recurse-submodules -j8 https://github.com/elastos/Elastos.Trinity.git ${WORK_DIR}/Elastos.Trinity
+  if [ ! -d "${WORK_DIR}/Elastos.Trinity" ]
+  then 
+    mkdir -p ${WORK_DIR} 
+    git clone --recurse-submodules -j8 https://github.com/elastos/Elastos.Trinity.git ${WORK_DIR}/Elastos.Trinity
+  fi 
+  cd ${WORK_DIR}/Elastos.Trinity && git pull --recurse-submodule
   cd ${WORK_DIR}/Elastos.Trinity/Dapps && git checkout master && git pull
   cd ${WORK_DIR}/Elastos.Trinity/Launcher && git checkout master && git pull
   cd ${WORK_DIR}/Elastos.Trinity/Plugins && git checkout master && git pull
@@ -295,7 +328,14 @@ function install_dependencies () {
   cd ${WORK_DIR}/Elastos.Trinity/ToolChains && git checkout master && git pull
 
   echo "Installing python dependencies..."
-  pip install -r ${WORK_DIR}/Elastos.Trinity/ToolChains/native/tools/requirements.txt
+  case `uname` in
+    Linux )
+      pip install -r ${WORK_DIR}/Elastos.Trinity/ToolChains/native/tools/requirements.txt 
+    ;;
+    Darwin )
+      ARCHFLAGS="-Wno-error=unused-command-line-argument-hard-error-in-future" pip install -r ${WORK_DIR}/Elastos.Trinity/ToolChains/native/tools/requirements.txt 
+    ;;
+  esac
 }
 
 function setup_env () {
@@ -315,8 +355,8 @@ function setup_env () {
   ${SED} -i'' '/The app manifest must contain the application DID string to be able to secure intents/,+4 d' ${WORK_DIR}/Elastos.Trinity/ToolChains/native/bin/build_from_source
 }
 
-setup_env
-python $WORK_DIR/Elastos.Trinity/ToolChains/native/bin/build_from_source --app ${ABSOLUTE_PATH}
+setup_env || stop_script "Could not successfully setup the environment"
+python ${WORK_DIR}/Elastos.Trinity/ToolChains/native/bin/build_from_source --app ${ABSOLUTE_PATH}
 
 retVal=$?
 if [ $retVal -eq 0 ]; then
